language: scala
jdk:
  - oraclejdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: TEST="compile"
      script: sbt compile
    - stage: release
      script: sbt ci-release
